### PR TITLE
Update Vaultka Info

### PR DESCRIPTION
**Pull request by 0xKMG**
remove the fork information since most of the current vaults are using original, customized code base.

### CODE REVIEW

**Comment by 0xKMG** [comment]
hi any update? thanks.

**Comment by realdealshaman** [comment]
Hey, @0xKMG thanks for the PR. Do you recognize the account that submitted this original pull request? https://github.com/DefiLlama/DefiLlama-Adapters/pull/5297
They added that it was a fork of Rage Trade there

**Comment by 0xKMG** [comment]
Yes I do, in fact we are in the same organization. I can log in to that account to verify

**Comment by it-posley** [comment]
yes, the forkedFrom information should be removed as code has been updated

**Comment by Vaultka** [comment]
> Hey, @0xKMG thanks for the PR. Do you recognize the account that submitted this original pull request? [DefiLlama/DefiLlama-Adapters#5297](https://github.com/DefiLlama/DefiLlama-Adapters/pull/5297) They added that it was a fork of Rage Trade there

Hi, I submitted the original pull request. Agree that forkedFrom information can be removed as code has been updated

**Pull request closed without merging**
