### PR TITLE
Update SFT Protocol metadata

### PR DESCRIPTION
**Pull request by Sunnight-wj**

### CODE REVIEW

**Comment by Define101** [comment]
@Sunnight-wj What is the purpose of this PR?

**Comment by Sunnight-wj** [comment]
> @Sunnight-wj What is the purpose of this PR?

update SFT Protocol official website url and description

**Comment by Sunnight-wj** [comment]
> @Sunnight-wj What is the purpose of this PR?

oh, I forgot to pull the repo before updating the metadata, and the metadata is listed in data3.ts now. I will update this and push again.

**Comment by Sunnight-wj** [comment]
Coud you handle this PR? @Define101

**Comment by Define101** [comment]
@Sunnight-wj this website still looks good https://www.sftproject.io/
Why change the url and twitter links?

**Comment by Sunnight-wj** [comment]
> @Sunnight-wj this website still looks good https://www.sftproject.io/ Why change the url and twitter links?

@Define101 We conducted a comprehensive brand upgrade, updating the UI, domain name, logo, and more.The old website is still available but not be updated and will be taken down in the future.About the twitter links, it is missing one space.

**Comment by Sunnight-wj** [comment]
@Define101 Can you please handle this PR by the way:  https://github.com/DefiLlama/icons/pull/1405

**Comment by Define101** [comment]
> > @Sunnight-wj this website still looks good https://www.sftproject.io/ Why change the url and twitter links?
> 
> @Define101 We conducted a comprehensive brand upgrade, updating the UI, domain name, logo, and more.The old website is still available but not be updated and will be taken down in the future.About the twitter links, it is missing one space.

Is there any public information regarding that brand upgrade?

**Comment by Sunnight-wj** [comment]
> > > @Sunnight-wj this website still looks good https://www.sftproject.io/ Why change the url and twitter links?
> > 
> > 
> > @Define101 We conducted a comprehensive brand upgrade, updating the UI, domain name, logo, and more.The old website is still available but not be updated and will be taken down in the future.About the twitter links, it is missing one space.
> 
> Is there any public information regarding that brand upgrade?

@Define101 There is our community announcement:  https://t.me/SFTprotocol_ann/326

**Comment by Define101** [comment]
We have updated the website here
https://github.com/DefiLlama/defillama-server/pull/6535
1 category only

**Comment by Sunnight-wj** [comment]
> We have updated the website here #6535 1 category only

@Define101 Can you also update the description?

**Comment by Define101** [comment]
@Sunnight-wj https://github.com/DefiLlama/defillama-server/pull/6542

**Comment by Sunnight-wj** [comment]
> @Sunnight-wj #6542

@Define101 Thanks for your support! I saw the update of website and description on defillama, but the logo not, could you please    
also update the logo? The PR is here: https://github.com/DefiLlama/icons/pull/1405.

**Comment by Define101** [comment]
> > @Sunnight-wj #6542
> 
> @Define101 Thanks for your support! I saw the update of website and description on defillama, but the logo not, could you please also update the logo? The PR is here: [DefiLlama/icons#1405](https://github.com/DefiLlama/icons/pull/1405).

Should be live within 2 hours

**Pull request closed without merging**
