### PR TITLE
Added API3 as an oracle for Tropykus zkEVM

### PR DESCRIPTION
**Pull request by dacarva**
We just added API3 as the oracle provider for Tropykus zkEVM

### CODE REVIEW

**Comment by Define101** [comment]
Please provide information on how API3 is securing Tropykus zkEVM TVL.

**Comment by dacarva** [comment]
API3 provides the price feeds to calculate how much ETH and USDC in the protocol are worth in USD in order to calculate the TVL

**Comment by dacarva** [comment]
@Define101 can we proceed with the merge?

**Comment by dacarva** [comment]
@Define101 hi! Can you please take a look at this?

**Comment by realdealshaman** [comment]
Hi @dacarva can you like any docs or public statements where API3 is mentioned as the oracle?

**Comment by dacarva** [comment]
Sure! 
https://medium.com/api3/tropykus-to-launch-on-polygon-zkevm-using-api3s-data-feeds-710fdc29b1c8
https://ecosystem.api3.org/ecosystem/tropykus-finance

**Pull request merged**
