### PR TITLE
Add Chainlink on Base for Synfutures v3

### PR DESCRIPTION
**Pull request by JoaoVasques**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @JoaoVasques thanks for the PR! Are there some docs available that indicate Chainlink is the primary oracle for base chain?

**Comment by JoaoVasques** [comment]
Hey @realdealshaman . Sure here is a [link](https://docs.synfutures.com/oyster-amm/protocol-parameters/base-network) to their docs where they explicitly mention Chainlink as one of the allowed Oracle Types

**Comment by JoaoVasques** [comment]
Hey @realdealshaman can you check again please?

**Comment by realdealshaman** [comment]
merged

**Pull request merged**
