### PR TITLE
update merlin info

### PR DESCRIPTION
**Pull request by CryptoSnowPrince**
I updated merlin project infomation

### CODE REVIEW

**Comment by Define101** [comment]
Why remove the fork field information? 
Also, we don't use the field audit_notes, so if you could remove it

**Comment by CryptoSnowPrince** [comment]
That's because this project is not same logic to uniswap.
And I agree to remove the field audit_notes if llama team don't use.

**Comment by CryptoSnowPrince** [comment]
I removed audit_note

**Comment by CryptoSnowPrince** [comment]
Thank you for your merge.
I want to ask why I can't see only 2 tokens on tvl charts.
As you kwow, in my project, there are some other tokens such as MAGE, MUTE etcs.

**Pull request merged**
