### PR TITLE
winr protocol change of oracle information

### PR DESCRIPTION
**Pull request by allinJB**

### CODE REVIEW

**Comment by Define101** [comment]
Please provide information on how Pyth secure your project TVL
Also any links are appreciated

**Comment by allinJB** [comment]
Pyth network secure our project with their price oracles. We heavily use them for both JustBet and Degen projects. Their Price feeds gives us instant price for our Winr Vault. 

https://pyth.network/

**Comment by allinJB** [comment]
These are the contracts we use Pyth Protocol  for price feeds

ETH Pool
https://arbiscan.io/address/0xCa764FFFf761F61D66A3C7B94d190668b90725d8
BTC Pool
https://arbiscan.io/address/0x183252D33b752f5e4933fB87c22e6f4Ad4793082
ARB Pool
https://arbiscan.io/address/0x8Ca48A0cE57C0F386f2FF3a56CCBc980BCa4B6AB
SOL Pool
https://arbiscan.io/address/0x48D68ED0E7F9a4244c5D689eDac6c1328300148E
GMX Pool
https://arbiscan.io/address/0xb2319DBEf51712B9B1c5944cC08fB1FbffF3497e
GRAIL Pool
https://arbiscan.io/address/0xCB4F8894e7A3ebb7Dc6a1993fA28EdbBc7b77C7E
TIA Pool
https://arbiscan.io/address/0x2BAf1280ab2D8fA3b2c6FBBe8E2A7c7986e2ae7c
JTO Pool
https://arbiscan.io/address/0x97457548B7D7892E367bDd2C8E5bb6c3EfCbED0f
RLB Pool
https://arbiscan.io/address/0xA89C30b0882D95B5a2ca5b5C87595F5Ad61230cC
AVAX Pool
https://arbiscan.io/address/0xffcc94a6326f60F78Abc781B9d618d365200aad4
BONK Pool
https://arbiscan.io/address/0xA8B3D4a24d71FDcb34c33C7bfB471F380Ffb0805
PEPE Pool
https://arbiscan.io/address/0x56b55C6c9D0503B94f714B722e95ce8b94cBb6d7
ORDI Pool
https://arbiscan.io/address/0x1a8f3F1Bc53a61469E81F5f46dD70754043Ec24c
INJ Pool
https://arbiscan.io/address/0x48759dcA06247Bf9147f1b7ba05e225Eca485969
SUI Pool
https://arbiscan.io/address/0xdDD1846b2d76D3693B1675C993f4BEd60cbFAcAc
SEI Pool
https://arbiscan.io/address/0xd525c16fe758312cDDA1D16aC412124c8c981927

**Comment by Define101** [comment]
JustBet and Degen are the only projects using WINR Protocol backend correct?

**Comment by allinJB** [comment]
Yes

**Comment by Define101** [comment]
Do you guys also use the chainlink oracles? 
From this 
https://github.com/winrprotocol/WINR_Protocol/blob/main/contracts/core/OracleRouterSimple.sol#L12
https://github.com/winrprotocol/WINR_Protocol/blob/main/contracts/core/OracleRouterV3.sol#L11

**Comment by allinJB** [comment]
We use GMX feed for swaps on WLP feed, however, degens.bet fully uses Pyth oracles for any on-demand price while opening and closing a position. In this regard, Pyth secures the whole TVL on WINR Liquidity Pool (WLP).

For reference, we no longer use Supra at all, and migrated completely to WINR VRF.

**Pull request merged**
