### PR TITLE
Update info about Witnet and protocols that use its oracle

### PR DESCRIPTION
**Pull request by aesedepece**
Howdy llama frens!

Witnet Sheriff here contributing some updates on the Witnet chain, and several protocols that are using the Witnet oracle.

Sources:
- Toucan Protocol: https://medium.com/witnet/witnet-securing-toucan-protocol-193690ef055a
- Argo Finance: https://medium.com/witnet/the-witnet-foundation-funding-argo-protocol-95b0227fbdec
- QiDao: https://medium.com/witnet/qidao-getting-price-feeds-and-security-from-the-witnet-oracle-9a33b2c6ee0b
- Goledo: https://twitter.com/witnet_io/status/1643235818776002565 and https://user-images.githubusercontent.com/1316439/229831006-0baec4f7-f398-41e9-a04a-5407aa7b4747.png

### CODE REVIEW

**Comment by 0xngmi** [comment]
ty for the PR!

Do these protocols use Witnet for their deployments on all chains or only for some chains?

**Comment by aesedepece** [comment]
> ty for the PR!
> 
> Do these protocols use Witnet for their deployments on all chains or only for some chains?

With Toucan we're live only on Celo and with QiDao it's only on Kava for now. How should we handle those? Thanks @0xngmi !

**Comment by Define101** [comment]
Thanks for letting us know
We have made the changes here https://github.com/DefiLlama/defillama-server/pull/2844

Regarding QiDAO will not be possible since we are not tracking kava chain in the adapter https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/qidao/index.js

**Comment by aesedepece** [comment]
Thanks, the `oraclesByChain` key is very helpful!

Any chance to update the info from commit e78f61f12e078656e78c927990367ed930e6155b?

**Comment by Define101** [comment]
I am sorry aesedepece. Complete miss that part
We have updated it here https://github.com/DefiLlama/defillama-server/commit/bb8b5bf5510dddac3f907c8dcac4efe3ef62488d
Should be live within 1 hour

**Pull request closed without merging**
