### PR TITLE
add covo finance oracle

### PR DESCRIPTION
**Pull request by mariobern**
gm llama sirs, 

requesting your review to add Pyth as the oracle for both Covo V1 and V2

https://covo-finance.gitbook.io/covo/trading/orders/order-settlement

https://covo-finance.gitbook.io/covo/trading/orders/order-settlement

thank you

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @mariobern , thank you for the PR, can you provide info on the markets that use Pyth? It is my understanding from the info in the link that only markets not supported by chainlink use Pyth

**Comment by mariobern** [comment]
Hey, yes so I believe the way it works is that currently all markets use Pyth, with Chainlink as the secondary oracle. If Covo lists a market that's not supported by Chainlink, it will use only Pyth as the oracle.

I can get you a written confirmation from the Covo team that this is indeed the case

**Comment by realdealshaman** [comment]
@mariobern that would be great to have here for reference, I was looking for a discord for them but could not find it. We can add Pyth as the only oracle if it is the main oracle 👍

**Comment by mariobern** [comment]
Covo
@realdealshaman let me know if you need anything else sir, thank you 🙏

**Comment by 0xngmi** [comment]
could you ask them what would happen if pyth price fees were wrong? could all tvl be drained?

**Comment by mariobern** [comment]
@0xngmi @realdealshaman attaching the answer from Covo

Covo pt2

**Pull request merged**
