### PR TITLE
Uncomment SkullSwap - and fix token info

### PR DESCRIPTION
**Pull request by chimpydev**
- Fix the skull token address

### CODE REVIEW

**Comment by Define101** [comment]
Hello chimp
Are you from SkullSwap team? Can we uncomment the protocol already?

**Comment by realdealshaman** [comment]
@chimpydev Hey, we need to wait until SkullSwap has some TVL to uncomment it. We don't list projects when they don't have any tvl. If you can ping us once some deposits have been made, we can get it uncommented and do the announcement for it

**Comment by chimpydev** [comment]
> Hello chimp Are you from SkullSwap team? Can we uncomment the protocol already?

Yes bro im from SkullSwap team! Yes yu can uncomment please, we have already passed the 5M in TVL and really need to have it listed on Defillama

**Comment by realdealshaman** [comment]
this is now listed and live on the Defillama website, will close this PR.

**Pull request closed without merging**
