### PR TITLE
Update data3.ts for suilend

### PR DESCRIPTION
**Pull request by nope-finance**
adding oracle data and link to audit(s)

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @nope-finance, thanks for the PR! Could you also provide docs or link to an announcement citing Pyth as the oracle? We're working on including these details with oracle listings for greater clarity. Appreciate it!

**Comment by nope-finance** [comment]
dont really have anything like that. i can send and example txn if you want?

**Comment by realdealshaman** [comment]
Hey @nope-finance I've merged the pr but can you still provide the txn? I'd like to take a look, thanks :pray:

**Comment by nope-finance** [comment]
sure yeh
https://suiscan.xyz/mainnet/tx/EXbC8hs3hYQvvvEDttWkTWxEnmJCyWmP7ppH11uKNbKW
here is a recent random withdrawal, you can see it pulls pyth prices then does the withdrawal

**Pull request merged**
