### PR TITLE
Update Deri Protocol Info

### PR DESCRIPTION
**Pull request by daniel-deri**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @daniel-deri thanks for the PR. There are a couple of things that I want to review before merging

chain: "Binance",, this portion of the listing indicates the first chain Deri Protocol , is we started tracking BSC tvl we can't update that portion to Arbitrum since it would attribute initial tvl to Arbitrum, even if Arbitrum was not live during the initial days

Also, do you have any documentation on how Pyth is being used within Deri? How much of the TVL would be at risk if Pyth oracles failed?

**Comment by daniel-deri** [comment]
> Hi @daniel-deri thanks for the PR. There are a couple of things that I want to review before merging
> 
> chain: "Binance",, this portion of the listing indicates the first chain Deri Protocol , is we started tracking BSC tvl we can't update that portion to Arbitrum since it would attribute initial tvl to Arbitrum, even if Arbitrum was not live during the initial days
> 
> Also, do you have any documentation on how Pyth is being used within Deri? How much of the TVL would be at risk if Pyth oracles failed?

hi @realdealshaman  Regarding the Binance section, I understand. Since the field's purpose is to track our initial TVL, there's no need for changes.

For the use of Oracle, please refer to: https://docs.deri.io/how-it-works/oracle. The Oracle is crucial for us; if the Oracle mechanism fails, all of DERI's TVL could be at risk.

**Comment by realdealshaman** [comment]
@daniel-deri can you help me understand what assets are using Oraclum and which are using Pyth? Also is Chainlink still used in Deri Protocol?

**Comment by daniel-deri** [comment]
> @daniel-deri can you help me understand what assets are using Oraclum and which are using Pyth? Also is Chainlink still used in Deri Protocol?

We use Pyth for following assets, while Oraclum is used for BTC and ETH

GBPUSD
EURUSD
XAUUSD
XAGUSD
QQQUSD
SPYUSD
AAPLUSD
AMCUSD
GOOGUSD
GMEUSD
MSFTUSD
GSUSD
IBMUSD
TSLAUSD
NFLXUSD
NKEUSD
INTCUSD
WMTUSD
MCDUSD
JPMUSD
GEUSD
DISUSD
COINUSD
AUDUSD
AMZNUSD
USDJPY

**Comment by realdealshaman** [comment]
Thanks, the applicable changes were applied manually

**Pull request closed without merging**
