### PR TITLE
feat: update APX Finance oracles

### PR DESCRIPTION
**Pull request by bryansniyve**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @bryansniyve thanks for the PR! Can you provide some docs or proof that Pyth is the primary oracle used at APX Finance

**Comment by apollox-docs** [comment]
> 嘿@bryansniyve感谢 PR！您能否提供一些文档或证据来证明 Pyth 是 APX Finance 使用的主要预言机

Proof：
https://medium.com/apx-finance/apx-v2-integrates-with-pyth-network-for-enhanced-real-time-price-accuracy-and-security-31d0ba5fb2b0

https://www.apollox.finance/en/futures/v2/BTCUSD (Pyth logo on APX website)

**Comment by realdealshaman** [comment]
https://medium.com/apx-finance/apx-v2-integrates-with-pyth-network-for-enhanced-real-time-price-accuracy-and-security-31d0ba5fb2b0

This says that Pyth is a backup oracle, not the primary

**Comment by bryansniyve** [comment]
> https://medium.com/apx-finance/apx-v2-integrates-with-pyth-network-for-enhanced-real-time-price-accuracy-and-security-31d0ba5fb2b0
> 
> This says that Pyth is a backup oracle, not the primary
image

This announcement says that Pyth is primary oracle,  Binance Oracle is backup oracle. please check it again, Thank you very much.

**Pull request closed without merging**
