### PR TITLE
Update data2.ts

### PR DESCRIPTION
**Pull request by Shashank729**
Update GooseFx protocol category from 'Derivatives' to 'Dexes'

### CODE REVIEW

**Comment by Shashank729** [comment]
Hey @Define101, can we get an update on this from your end?

**Comment by Define101** [comment]
Just checked the Farm section. Majority of the TVL is coming from there.
But for example, when a user executes a 10x trade, where does that 9x liquidity come from?
If I open a 10$ position with a 10x leverage, my position would be 100$, my question would be where are these 90$ coming from? From those pools on the  farm section right?

**Comment by Define101** [comment]
Thanks for the clarification @usgoose 
The current tvl of the trade product is very low (goosefx.io/trade), but since we are not tracking we could track it under a new listing with the category derivatives
Regarding your Farms section, they would fit better under the category Yield no?

**Comment by g1nt0ki** [comment]
just so I understand, in the farm/AMM section, users can provide liquidity, but no option to trade directly in the UI, but instead trade through jup.ag?

**Comment by Define101** [comment]
@usgoose Thanks for the explanation
We will merge this PR

**Pull request merged**
