### PR TITLE
update Monocerus Information (Update data3.ts)

### PR DESCRIPTION
**Pull request by pullstacker**
Add Manta Information and Update several fields

### CODE REVIEW

**Comment by Define101** [comment]
We made the changes here https://github.com/DefiLlama/defillama-server/pull/5439
We can only track one token (one chain)

**Comment by pullstacker** [comment]
> We made the changes here #5439 We can only track one token (one chain)

hi we've already remove the second token, thanks!

**Comment by pullstacker** [comment]
Screenshot_20240105_213858_Chrome
as for the second chain, the other contributor asked me to keep it, pls refer to attached screenshot

**Comment by pullstacker** [comment]
> We made the changes here #5439 We can only track one token (one chain)

hi, is there anything else that we should fix beside the token?

**Comment by Define101** [comment]
> > We made the changes here #5439 We can only track one token (one chain)
> 
> hi, is there anything else that we should fix beside the token?

We just made all the changes. We cant add the audit because its a token audit. We cant change category because what we are tracking is your dex product.

**Comment by Define101** [comment]
manta: 0x657218E3535B32EDef9a722E35dcd6EA40E1202e

**Comment by Define101** [comment]
Yes sir
Should be live within 1 hour

**Comment by pullstacker** [comment]
> Yes sir Should be live within 1 hour

perfect  ser, many thanks for your best support!

**Pull request closed without merging**
