### PR TITLE
update roup category

### PR DESCRIPTION
**Pull request by butcher-blaviken**
update roup category

### CODE REVIEW

**Comment by Define101** [comment]
Hello, was trying to see how roup works. Seems that its a bridge only correct? You can bridge this assets, back and forth. But you can send  roup token for example from mapo and get other token on bitcoin correct?
image

**Comment by butcher-blaviken** [comment]
Yes, you're right

**Comment by Define101** [comment]
Okok. So the category needs to stay bridge

**Comment by realdealshaman** [comment]
Closing this due to inactivity, feel free to open another if any further review is needed

**Pull request closed without merging**
