### PR TITLE
add Synthetix under Pyth TVS

### PR DESCRIPTION
**Pull request by mariobern**
gm llama sers

would like your help to review Pyth as another oracle for Synthetix

They have been a strong supporter since late last year and we want to add them under Pyth TVS

https://twitter.com/PythNetwork/status/1595099857231831041?s=20

https://twitter.com/synthetix_io/status/1601280873965371392?s=20

Thank you sers

### CODE REVIEW

**Comment by mariobern** [comment]
No numbers unfortunately but we're pretty much SNX primary oracle on Optimism 

We had this discussion a few months back about being able to add TVS for a protocol in a specific chain (provided the protocol is on multiple chains)

**Comment by 0xngmi** [comment]
so atm the way our code works is that all tvl of a protocol is attributed to their oracles, we don't have a way to split it, doing so would require new changes to our backend code

**Comment by mariobern** [comment]
Would it be possible to add Pyth alongside Chainlink as the oracle for Synthetix for now? and once we can split the TVL, we don't mind to be placed to be just under Optimism

**Comment by mariobern** [comment]
https://dune.com/queries/1898719/3129122

Based on this Dune stats, TVL for SNX on Optimism is around 230M

**Pull request closed without merging**
