### PR TITLE
WIP: Lists Giveth to protocol

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Comment by Define101** [comment]
Hello
Could you guys also provide an adapter with some code to count your TVL?
https://docs.llama.fi/list-your-project/submit-a-project

**Comment by mateodaza** [comment]
> Hello Could you guys also provide an adapter with some code to count your TVL? https://docs.llama.fi/list-your-project/submit-a-project

Oh understood! I was working on [this](https://github.com/DefiLlama/yield-server) but I think it's another thing. 

I'll put this as a WIP until I get it done. Will ping you when it's ready. Thanks :)

**Comment by realdealshaman** [comment]
was getting some errors. I've used the info you provided to add the listing and it should be live on the website in about one hour 👍

**Comment by mateodaza** [comment]
You rock @realdealshaman! Thank you

**Pull request closed without merging**
