### PR TITLE
Metavault graphics low-resolution fixed.

### PR DESCRIPTION
**Pull request by 0xrmvdao**
After re-branding, our project logos has low-resolution problem on small-sized icons. We fixed them and update latest project info.

### CODE REVIEW

**Comment by Define101** [comment]
Hello guys, I have made the changes regarding the logos
However don't understand the reason to change the category/ remove the Fork information, could you explain it, please?
And btw when I click on launch app I get this error 
image
image

**Comment by 0xrmvdao** [comment]
Thank you for your support. Sure, we are not anymore a fork of olympus, that was the state as we are on Fantom. with the Ethereum migration we changed nearly all smart contracts and so on
https://metavault.medium.com/trading-of-mvd-stopped-eth-migration-f0a104a2c503

MVD is not a rebase token anymore.

also thank you for letting us to know, we will resolve the ipfs domain issue soon

**Comment by Define101** [comment]
Thank you so much for the information
Seems that Metavault fits better into the Services category, what do you guys think?
Regarding the link, it is working now 
image

**Comment by Define101** [comment]
Final changes have been made and will reflect within 1 hour
Thank you so much

**Pull request closed without merging**
