### PR TITLE
Update Level protocol information

### PR DESCRIPTION
**Pull request by davidlee1435**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @davidlee1435 thanks for the PR! However we don't have a category "Stablecoin". Please choose a category from this list: https://defillama.com/categories. Thank you

**Comment by davidlee1435** [comment]
@realdealshaman just updated to remove the category for now!

**Comment by realdealshaman** [comment]
@davidlee1435 sorry, listings need to have a category

**Comment by realdealshaman** [comment]
Looking at your Docs it seems "Yield" would be a fitting category since users are depositing stablecoins into your protocol to earn a yield in the form of the interest bearing token lvlUSD

**Comment by realdealshaman** [comment]
@davidlee1435 can we close this PR?

**Comment by realdealshaman** [comment]
updated the name and category, closing this PR for now, please open a new one for further changes. Thanks

**Pull request closed without merging**
