### PR TITLE
Enable position exchange for both binance and posichain

### PR DESCRIPTION
**Pull request by dannyposi**

### CODE REVIEW

**Comment by Define101** [comment]
Hello dannyposi
Seems that the current adapter is not counting the TVL in the Posichain.
If you could add some code to count the TVL in the Posichain would be great

**Comment by Define101** [comment]
Hello Danny 
Saw your other PR
Everything about listing the posichain is done already. We just need one protocol to use it 
https://docs.llama.fi/list-your-project/submit-a-project

**Comment by dannyposi** [comment]
Thanks @Define101 i'm updating tvl on other MR

**Comment by dannyposi** [comment]
@Define101 my colleague has updated TVL on this MR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3722
Please help to check

**Comment by dannyposi** [comment]
@Define101 can you back to this PR?

**Comment by Define101** [comment]
Hello Danny, seems the PR you are mentioned only has TVL for Bsc chain
Is there any other protocol using posichain ?

**Comment by Define101** [comment]
Closing this PR , anything else feel free to let us know

**Pull request closed without merging**
