### PR TITLE
Update data3.ts (StackingDAO)

### PR DESCRIPTION
**Pull request by philiphacks**
We had a rebrand (see https://www.stackingdao.com/) so dropping the new logo here too, thanks for your help on getting this updated!

stackingdao

### CODE REVIEW

**Comment by Define101** [comment]
Should be live within 2 hours
https://github.com/DefiLlama/defillama-server/pull/6529

**Comment by philiphacks** [comment]
@Define101 thanks!

it doesn't seem to be live yet
image

https://defillama.com/chain/Stacks

**Comment by Define101** [comment]
@philiphacks make sure you refresh the page
image

**Comment by philiphacks** [comment]
@Define101 yes - after a hard refresh it's working now, ty ser!

**Pull request closed without merging**
