### PR TITLE
chore: Update Dyson Finance information

### PR DESCRIPTION
**Pull request by anna-pelith**
chore: Update Dyson Finance information.

Dyson Finance has incorporated Pyth's pull oracle design to elevate the reliability and accessibility of financial data within its ecosystem.
https://docs.dyson.finance/mechanisms/dynamic-amm#dynamic-price-feeds-in-dyson-finance-pyth-oracle

### CODE REVIEW

**Comment by Define101** [comment]
The only product we are tracking on Dyson Finance is the dexes part (uniswap v2 fork) so there is no oracle involved

**Comment by anna-pelith** [comment]
> The only product we are tracking on Dyson Finance is the dexes part (uniswap v2 fork) so there is no oracle involved

OK, can you update other information? Or do I have to resend the PR without oracle? Thank you so much

**Comment by LeonWang0226** [comment]
Hi @g1nt0ki ,
I understand your confusion. Although the functions looks similar, Dyson Finance indeed differs significantly from Uniswap, showcasing the following distinctive features:

1. Dynamic Trading Fee Mechanism: Unlike Uniswap's fixed fee structure, Dyson Finance implements a dynamic trading fee mechanism. This mechanism takes into account the trading direction (buy and sell ) and trading volume, resulting in liquidity pools that dynamically adjust trading fees. This approach aims to capture Miner Extractable Value (MEV), optimize protocol fee income, and ensure a fair distribution of revenue among users.

2. Dual Investment Participation: In contrast to Uniswap, where users deposit funds directly into pools to provide liquidity, Dyson Finance introduces a unique approach. Users contribute liquidity to the pools through dual investment participation. It is essential to note that during the dual investment process, the system executes a virtual swap to calculate the output of token0 and token1 in the pool. This, in turn, updates the fee ratio, impacting the fair price within the pool.

These key features highlight the uniqueness of Dyson Finance compared to Uniswap. If you have any further questions, feel free to ask. Thank you.

**Comment by Define101** [comment]
https://github.com/DefiLlama/defillama-server/pull/5980 we made the changes here
Regarding the oracle
Could you please reply to this 3 questions
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

**Comment by anna-pelith** [comment]
After discussions with our Oracle supplier, we have decided not to include the oracle in our DEX product description on the DefiLlama website. Thank you for merging other necessary modifications into the main branch beforehand. However, we still have some essential changes that will be included in a new PR.

**Pull request closed without merging**
