### PR TITLE
Add IOLEND protocol

### PR DESCRIPTION
**Pull request by eriscrypt**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @eriscrypt this is already listed: IOLEND https://defillama.com/protocol/iolend#information

**Comment by realdealshaman** [comment]
I've now also added the missing token info and coingecko id as well as updated the description

**Comment by eriscrypt** [comment]
Hey ! I also update an icon

**Comment by realdealshaman** [comment]
thanks @eriscrypt. I've updated the icon and it will show the new one in about one hour

**Comment by realdealshaman** [comment]
new logo is now live, you may just need to clear cache to see it :+1: 

please let me know if we can close this pr

**Pull request closed without merging**
