### PR TITLE
edit oracle list: added supra to defi kingdom protocol

### PR DESCRIPTION
**Pull request by ksdumont**
Hi,
We would like to add the use of Supra's VRF Oracle to Defi Kingdoms. All of DFK's VRF services are supported by Supra. 

Materials
-> https://devs.defikingdoms.com/dfk-chain/ecosystem-partners/supraoracles-vrf
-> https://supraoracles.com/news/supraoracles-partners-with-defi-kingdoms-the-first-multi-chain-play-to-earn-game/
-> https://x.com/SupraOracles/status/1622681593960890368?s=20
-> https://qa-spa.supraoracles.com/academy/what-is-defi-kingdoms-kingdoms/

Rationale
Defi Kingdoms uses Supra's VRF oracle for all of their randomization needs. 

Thank you in advance. Let me know if you need any more info.

Best,
Keith

### CODE REVIEW

**Comment by realdealshaman** [comment]
@ksdumont, thanks for the PR. We only add oracles to our listings if they are crucial to the project's function, specifically where oracle failure could risk or drain user deposits

**Comment by ksdumont** [comment]
I would say this is pretty crucial, they use it in many of their smart contracts.

**Comment by realdealshaman** [comment]
@ksdumont, could you elaborate on how user deposits would be at risk if the oracle failed? We are particularly interested in tracking the total value secured by each oracle so understanding how they are safeguarding the tvl is essential

**Comment by ksdumont** [comment]
Ok, I understand so I should be adding just price feed oracles? Is there a separate section where you track VRF usage?

**Pull request closed without merging**
