### PR TITLE
update stream metadata

### PR DESCRIPTION
**Pull request by 0xDro**
update category, audit, and description for stream finance

### CODE REVIEW

**Comment by Define101** [comment]
Cant see the changes

**Comment by Define101** [comment]
Leave them here please as a comment

**Comment by 0xDro** [comment]
description: Stream offers exposure to market making opportunities and delta neutral strategies via decentralized strategies. In exchange for using this software, users may pay up to 10% in performance fees and Stream may keep more if it outperforms predicted APY. These strategies focus primarily on DEX and DeFi only trades. However in the event of reaching over capacity, Stream reserves the right to work with third parties such as major market makers to earn yield for users. If these positions are entered into there will be an announcement and it will be visible in the transparency dashboard.

audits: "1",

 category: "Derivatives",

**Comment by Define101** [comment]
Its live
Will close this PR
https://defillama.com/protocol/stream-finance

**Pull request closed without merging**
