### PR TITLE
add pyth powered protocols

### PR DESCRIPTION
**Pull request by mariobern**
gm llama sirs

requesting your review to add these 2 protocols under Pyth oracle

CoffeeDex 
https://x.com/coffee_vedex/status/1716823967087141119?s=20

Mu.exchange
https://docs.mu.exchange/available-pairs

thank you

### CODE REVIEW

**Comment by realdealshaman** [comment]
@mariobern thanks for the pr. We aren't adding oracles to solidly forks since they are just dexes similar to Uniswap. Some had incorrectly been added but I've removed those. We can add Pyth to Mu Exchange but adding it to Coffee Dex wouldn't be correct

**Comment by mariobern** [comment]
Thanks for the comment @realdealshaman, really appreciate it

Will remove CoffeeDex from the PR

In the meantime, we've just collaborated with two other protocols Unidex and Metavault. Here are the integration tweets to further verify

Unidex
https://x.com/UniDexFinance/status/1716862287498391783?s=20

Metavault
https://x.com/MetavaultTRADE/status/1719353616098844959?s=20

thank you

**Comment by realdealshaman** [comment]
@mariobern thanks for the follow up, Metavault V3 is actually just a Uniswap V3 fork, maybe Pyth is being used in in the derivatives product. Below is the id for the Metavault Derivatives adapter:

    id: "1801",
    name: "Metavault.Trade",

**Comment by mariobern** [comment]
@realdealshaman thank you!

much apologies, will fix this

**Pull request merged**
