### PR TITLE
Update data2.ts

### PR DESCRIPTION
**Pull request by covofin**
Update Info for COVO for Protocol Upgrade

### CODE REVIEW

**Comment by Define101** [comment]
Why remove Fork information?

**Comment by covofin** [comment]
We have upgraded our protocol to version 2, which is no longer a GMX fork and allows trading of even Forex and Metals, and we are completely deprecating version 1 and focus only on V2. The V2 adapter has already been approved and can be found at https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/covo-v2/index.js."

**Comment by covofin** [comment]
The V2 platform is totally different from GMX in terms of contracts and user interface. Unlike GMX, where all listed assets require a certain percentage of allocation in the pool like BTC, ETH, etc., On our V2 platform all trades are backed by the single USDC pool, which allows for leverage trading of any listed assets including Forex pairs like USD and EUR through Pyth and Chainlink oracles. This capability is not available on GMX, thus we are no longer a fork of GMX.

**Comment by Define101** [comment]
We have created a parentProtocol
Now we track V1 and V2 in different listings
I will keep GMX fork on Covo V1, and remove the fork information from Covo V2
Is this ok ?

**Comment by covofin** [comment]
Okay, this can work for V2.

**Comment by covofin** [comment]
Also, for Fees and Revenue tracking, can we somehow mention that current stats are for V1 only, as we are currently working on adaptors to track V2 Fees and revenue.

**Comment by Define101** [comment]
"can we somehow mention that current stats are for V1 only" We will point to Covo V1
Once there is an adapter for the v2 , there will be covo v1 and covo v2 on the fees dashboard

**Pull request closed without merging**
