### PR TITLE
Listing posichain

### PR DESCRIPTION
**Pull request by dannyposi**

### CODE REVIEW

**Comment by dannyposi** [comment]
@realdealshaman deploy failed, could you help to retry? https://github.com/DefiLlama/defillama-server/actions/runs/2901171242

**Comment by realdealshaman** [comment]
sure, will run again but I also want to add that for posichain to appear on the chains page, we will need to include an adapter that returns the tvl of a defi protocol running on posichain

**Comment by dannyposi** [comment]
@realdealshaman ok i will add. Do you have any MR sample to add a new chain to adapters?

**Comment by dannyposi** [comment]
Btw, could you check this MR: https://github.com/DefiLlama/defillama-app/pull/673

**Pull request merged**
