### PR TITLE
Re-branding MVD and MVX + MVD migrated from Fantom to Ethereum.

### PR DESCRIPTION
**Pull request by 0xrmvdao**
Re-branded MVD and MVX tokens. 

MVD migrated from Fantom to Ethereum mainnet. We updated contract address. 

We also added the new logos inside comment line. Please update the resources accordingly. 

Re-branded MVD  Logo: https://res.cloudinary.com/metavault/image/upload/v1660377189/metavault_logo_pwnpma.svg 

Re-branded MVX  Logo:  https://res.cloudinary.com/metavault/image/upload/v1660377763/MVX_Logo_fmnp7x.svg

### CODE REVIEW

**Comment by Define101** [comment]
Hello guys thanks for letting us know
Did you guys make the changes on the adapter already? To count TVL on ETH

**Comment by 0xrmvdao** [comment]
Thank you for your support,
the adapter for Metavault (TVL) we are just reworking, this we will hopefully submit today. We need to revise the adapter because we can no longer use the Ohm helper.

**Comment by 0xrmvdao** [comment]
Hello Team,

we've completed TVL implementation on Adapters project and committed changes. Here is the pull request: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3563

**Comment by Define101** [comment]
Hello 0xrmvdao
I am gonna close this PR
Already made the changes and should be live within 1 hour
Thank you for letting us know about the rebrand

**Pull request closed without merging**
