### PR TITLE
add 4Cast

### PR DESCRIPTION
**Pull request by 4Cast-Studio**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @4Cast-Studio, could you let me know what your project is about and if you've submitted a separate pull request to any of our repos for the dashboards?

**Comment by 4Cast-Studio** [comment]
4CAST is the Home of Degen Mini Games on Solana offering users a wide selection of mini-games. These range from multiplayer games like Wheel Spin, Crypto Price Prediction, and Lottery to single-player games such as Coin Flip and Plinko.

for more details, refer to 4cast docs: https://docs.4cast.win/4cast

We have submitted a pull request to add our fees adaptor.
https://github.com/DefiLlama/dimension-adapters/pull/1786

**Comment by realdealshaman** [comment]
Hey @4Cast-Studio, thanks for the PR and the info! I’ve manually added it to avoid merge conflicts, as the PR fell behind a few commits, making manual addition easier. Thanks again for the info and the logo

**Comment by realdealshaman** [comment]
https://x.com/DefiLlama/status/1826782104841322926

**Pull request closed without merging**
