### PR TITLE
Update data3.ts added SCALLOP SUI

### PR DESCRIPTION
**Pull request by salemalem**

### CODE REVIEW

**Comment by Define101** [comment]
Hello. The current code is only tracking Solana Chain

**Comment by salemalem** [comment]
@Define101

**Comment by Define101** [comment]
@salemalem we made the changes here https://github.com/DefiLlama/defillama-server/pull/6503

**Comment by Define101** [comment]
@salemalem Can we close this Pull Request?

**Comment by salemalem** [comment]
@Define101 yes sir

**Pull request closed without merging**
