### PR TITLE
Fix Hedge audits and logo

### PR DESCRIPTION
**Pull request by Haoqian-Zheng**

### CODE REVIEW

**Comment by Define101** [comment]
Hi guys just one question, why change from 2 to 3 on the audits?
Its an audit for your project right?
0 -> No audits
1 -> Part of this protocol may be unaudited
2 -> Yes
3 -> This protocol is a fork of an existing audited protocol

**Comment by Define101** [comment]
I see the problem , we had the number 2 on audits by mistake since you guys didn't have a audit (should had been a 0)
Gonna merge your PR , and change the number to 2 again

**Comment by Haoqian-Zheng** [comment]
Oh I see, I thought this was the number of audits we completed lol. 

We do have audits, see https://docs.hedge.so/protocol-overview/security but it wasn't showing on the site

**Comment by Define101** [comment]
Thanks for your PR 
The audit link should be live on the website within 1 hour

**Pull request merged**
