### PR TITLE
update tsunami finance metadata

### PR DESCRIPTION
**Pull request by yv-was-taken**
- update tsunami finance metadata
- change tsunami metadata and logo

### CODE REVIEW

**Comment by yv-was-taken** [comment]
Note. The logo, and logo name, which is reflected here, has been changed in this pr. currently pending: https://github.com/DefiLlama/icons/pull/1160

**Comment by Define101** [comment]
Changes here made https://github.com/DefiLlama/defillama-server/pull/5494

**Comment by Define101** [comment]
https://defillama.com/protocol/tsunamix
Can we close this Pull Request?

**Comment by yv-was-taken** [comment]
> https://defillama.com/protocol/tsunamix Can we close this Pull Request?

Closed, thanks!

**Pull request closed without merging**
