### PR TITLE
added_usdc_plus_overnight

### PR DESCRIPTION
**Pull request by Kron1749**
Added usdc plus ovenight

### CODE REVIEW

**Comment by Define101** [comment]
Sorry, we already had a listing
https://defillama.com/protocol/overnight-usd+

**Comment by Kron1749** [comment]
> Sorry, we already had a listing https://defillama.com/protocol/overnight-usd+

Hello, that's a USDC Plus,not USD Plus, that's 2 different tokens

**Comment by Define101** [comment]
@Kron1749 its already being tracked here https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/overnight-usdPlus/index.js#L9

**Comment by Kron1749** [comment]
> @Kron1749 its already being tracked here https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/overnight-usdPlus/index.js#L9

Yeah,it is,and TVL updated, thank you
But the problem is that USDC should be in here https://defillama.com/protocol/overnight-finance
But there is no USDC+ token

**Pull request closed without merging**
