### PR TITLE
fix: update address for kim

### PR DESCRIPTION
**Pull request by agileurbanite**
TVL is not updating on defillama for Kim need to update address to ensure that defillama updates tvl data:
https://defillama.com/chain/Mode

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi, @agileurbanite is that the address for the native token of Kim or is it something else?

If tvl should be higher, have you guys recently launched a new version with a new factory address?

**Comment by agileurbanite** [comment]
That's the new version of the factory address

**Comment by realdealshaman** [comment]
@agileurbanite that field is where the native token for KIM exchange will go when you have one, I've updated the factory address in the adapter that calculates the tvl here: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/kizuna/index.js

Thanks for the heads up! :+1:  Please don't hesitate to let us know of any new changes. Cheers

**Comment by realdealshaman** [comment]
The new tvl will show up with the next hourly update

**Pull request closed without merging**
