### PR TITLE
Update data3.ts

### PR DESCRIPTION
**Pull request by Tomwhh**
Update description and category for 21.co tokens

### CODE REVIEW

**Comment by Define101** [comment]
We made the changes here
https://github.com/DefiLlama/defillama-server/pull/6298

**Comment by Tomwhh** [comment]
Thanks @Define101 ! can we change the category as well from Bridge to Cross Chain?

**Comment by Define101** [comment]
@Tomwhh Not possible sorry

**Comment by Tomwhh** [comment]
@Define101 may I ask why? Is it because of the project not fitting the criteria?

**Pull request closed without merging**
