### PR TITLE
Add Traddify Arbitrage on Kava chain.

### PR DESCRIPTION
**Pull request by EVMlord**

### CODE REVIEW

**Comment by g1nt0ki** [comment]
@EVMlord is this in production?

**Comment by EVMlord** [comment]
> @EVMlord is this in production?

Yes, support for multichain would be coming soon.

**Comment by EVMlord** [comment]
> > > @EVMlord is this in production?
> > 
> > 
> > Yes, support for multichain would be coming soon.
> 
> I am bit confused by your PR, I dont see any activity in the contract, are you sure you want to count kava not wkava? we cant list projects with 0 tvl

Mainly Kava, but we would like to count both.

**Comment by realdealshaman** [comment]
Hey, thanks for the PR, added the listing manually since we have had a few others since this PR. It will be live on the website in about one hour

**Pull request closed without merging**
