### PR TITLE
add delta trade

### PR DESCRIPTION
**Pull request by Nicklaus6**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @Nicklaus6 thanks for the PR! I've updated our current listing with the info you've provided

{
    id: "5050",
    name: "Delta Trade",
    address: null,
    symbol: "-",
    url: "https://www.deltatrade.ai",
    description:
      "Delta Trade is a multi-chain decentralized trading protocol that enhances user capabilities with sophisticated on-chain trading strategies such as Grid Trading, DCA, Rebalancing Grid, MultiChain Support, OrderBook, Full Platform Market Making and AI Powered Strategy.It is designed to deliver a straightforward and intuitive user experience, making it exceptionally accessible for retail traders",
    chain: "Near",
    logo: `${baseIconsUrl}/delta-trade.jpg`,
    audits: "2",
    audit_note: null,
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Near"],
    oracles: ["Pyth"], // https://docs.deltatrade.ai/technical-information/security/oracle#pyth-oracle
    forkedFrom: [],
    audit_links: [
      "https://github.com/blocksecteam/audit-reports/blob/main/rust/blocksec_deltatrade_v2.0_signed.pdf",
      "https://github.com/blocksecteam/audit-reports/blob/main/rust/blocksec_deltatrade_DCA_v1.0-signed.pdf",
    ],
    module: "deltatrade.js",
    twitter: "DeltaBotTeam",
    listedAt: 1724748009
  },

let me know if it is okay to close this pull request, thank you

**Comment by Nicklaus6** [comment]
> Hey @Nicklaus6 thanks for the PR! I've updated our current listing with the info you've provided
> 
> { id: "5050", name: "Delta Trade", address: null, symbol: "-", url: "https://www.deltatrade.ai", description: "Delta Trade is a multi-chain decentralized trading protocol that enhances user capabilities with sophisticated on-chain trading strategies such as Grid Trading, DCA, Rebalancing Grid, MultiChain Support, OrderBook, Full Platform Market Making and AI Powered Strategy.It is designed to deliver a straightforward and intuitive user experience, making it exceptionally accessible for retail traders", chain: "Near", logo: `${baseIconsUrl}/delta-trade.jpg`, audits: "2", audit_note: null, gecko_id: null, cmcId: null, category: "Yield", chains: ["Near"], oracles: ["Pyth"], // https://docs.deltatrade.ai/technical-information/security/oracle#pyth-oracle forkedFrom: [], audit_links: [ "https://github.com/blocksecteam/audit-reports/blob/main/rust/blocksec_deltatrade_v2.0_signed.pdf", "https://github.com/blocksecteam/audit-reports/blob/main/rust/blocksec_deltatrade_DCA_v1.0-signed.pdf", ], module: "deltatrade.js", twitter: "DeltaBotTeam", listedAt: 1724748009 },
> 
> let me know if it is okay to close this pull request, thank you

Thank you for the response @realdealshaman. However, I have a question: why was our category changed from "Dexes" to "Yield"? Our product is a decentralized Grid and DCA strategy. Please help set our category back to "Dexes." Thank you!

**Comment by realdealshaman** [comment]
@Nicklaus6 I've updated the listing to Dexes

**Comment by Nicklaus6** [comment]
> @Nicklaus6 I've updated the listing to Dexes

I see the category now, but where is the oracle?

**Comment by realdealshaman** [comment]
@Nicklaus6 when an oracle is added to the listing, your project gets added to the oracle page, it does not appear on your protocol page
image

**Comment by Nicklaus6** [comment]
> @Nicklaus6 when an oracle is added to the listing, your project gets added to the oracle page, it does not appear on your protocol page image

@realdealshaman Thanks for your help! By the way, if I add volume to the dimension adapters, will volume appear on the protocol page?

**Comment by realdealshaman** [comment]
@Nicklaus6 yes it will

**Pull request closed without merging**
