### PR TITLE
chore: Add dexter as protocol

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @abhimanyusinghgaur  , thank you for the PR, it's much appreciated. Having this info is definitely helpful. We will add it to the file once we have an adapter for Dexter, but it looks like it's currently only available on testnet. Could you please let us know when it goes live so that we can look into pulling its TVL? Thank you again

**Comment by Define101** [comment]
https://github.com/DefiLlama/defillama-server/pull/2680

**Comment by Define101** [comment]
Should be live within 1 hour.

**Comment by Define101** [comment]
https://defillama.com/protocol/dexter

**Pull request closed without merging**
