### PR TITLE
add new protocols using Pyth

### PR DESCRIPTION
**Pull request by mariobern**
gm 

requesting your review to add protocols using Pyth:

Bakerfi
https://twitter.com/bakerfi_/status/1765391913346277481?s=20

Goledo
https://goledo-1.gitbook.io/goledo-docs/about-goledo/goledo-overview/price-oracle

Neptune
https://docs.nept.finance/developers/price-oracle-queries

thank you

### CODE REVIEW

**Comment by mariobern** [comment]
Synfutures V3:
https://docs.synfutures.com/docs/User-Guide/Protocol-Parameters

**Comment by mariobern** [comment]
BFX Blast Futures:
https://docs.blastfutures.com/get-started/dynamic-amm#how-it-works
image

**Comment by Define101** [comment]
Hello if you could reply to this questions would be great. 

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

Also any contract address would be great to confirm how they using Pyth Oracle

**Comment by Define101** [comment]
image
SynFutures v3

**Comment by mariobern** [comment]
Bakerfi:
_We've already deployed oracles for wstETH/USD and ETH/USD on Arbitrum, marking the beginning of a new era for BakerFi's operations. And this is just the start!_

Goledo:
https://x.com/GoledoFinance/status/1735081251973795852?s=20
_Goledo is pleased to announce that it has implemented Pyth as the new pricing oracle solution for the lending pool._

Neptune:
_Prices can be queried with GetPrice{ .. }, GetPrices{ .. }, and GetAllPrices{ .. }. Neptune's price feeds are powered by Pyth and Injective chain data._

For Synfutures V3, since it operates exclusively on Blast (where Chainlink and Uniswap are not live), they are using Pyth as the sole price feed provider. https://docs.synfutures.com/docs/User-Guide/Pair-Specifications

Blast Futures:
_The BFX DAMM aggregates real-time bid/ask prices from numerous top centralised, decentralised exchanges and oracles such as Pyth to update the price levels of the AMM strategy with millisecond accuracy._

**Comment by realdealshaman** [comment]
Hi @mariobern , I've added these manually and updated synfuturesv3 so that it shows the breakdown by chain, keeping pyth as the oracle on blast

For Goledo, can you provide what assets are using Pyth, if Pyth assets make up more than 50% of the TVL we can remove Witnet

**Comment by mariobern** [comment]
Hey @realdealshaman thanks for the comment

Will work with Goledo and ask for more details on the assets, in the meantime we can remove Pyth as the oracle securing Goledo from the PR

**Comment by realdealshaman** [comment]
Hey @mariobern I've added the others manually to avoid merge conflicts, I will close this pr now since we've resolved on Goledo

**Pull request closed without merging**
