### PR TITLE
update shoebill-v2 data

### PR DESCRIPTION
**Pull request by ShoebillFinance**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @ShoebillFinance , happy to get this merged but, do you have a reference link we can add that indicates that Pyth is securing the tvl of your protocol? Is it the only oracle used or is it only used for certain coins? Also, is it the oracle used on everychain or only on a specific chain? Thanks in advance

**Comment by ShoebillFinance** [comment]
Hello Real Shaman,

We're using Pyth on WEMIX chain for WEMIX coin.
On Manta, we're using Chainlink for ETH and USDC but from BNB Chain and
transfer it through our own server, but will change it to Redstone in a few
weeks.
On Klaytn, we're using Witnet for KLAY.

Please let me know in case you need any other information.

Thanks,


2024년 1월 11일 (목) 오전 11:11, Real Shaman ***@***.***>님이 작성:

**Comment by ShoebillFinance** [comment]
For your reference,

WEMIX Pyth
https://wemixscan.com/address/0xa2aa501b19aff244d90cc15a4cf739d2725b5729

Shoebill's oracle contract using WEMIX Pyth
https://wemixscan.com/address/0x357176731Cac68B70b4bFA6cAc28A216c769feCc

2024년 1월 13일 (토) 오전 12:21, Shoe Bill ***@***.***>님이 작성:

**Comment by ShoebillFinance** [comment]
For your reference2, here's our docs indicating the oracles
https://docs.shoebill.finance/risk/oracle

so, wrapping up,
We're using Pyth on WEMIX chain for WEMIX coin.
On Manta, we're using Chainlink for ETH and USDC but from BNB Chain and
transfer it through our own server, but will change it to Redstone in a few
weeks.
On Klaytn, we're using Witnet for KLAY.
WEMIX Pyth
https://wemixscan.com/address/0xa2aa501b19aff244d90cc15a4cf739d2725b5729
Shoebill's oracle contract using WEMIX Pyth
https://wemixscan.com/address/0x357176731Cac68B70b4bFA6cAc28A216c769feCc

Please let me know in case you need any other information.

Thanks,

2024년 1월 13일 (토) 오전 12:27, Shoe Bill ***@***.***>님이 작성:

**Comment by ShoebillFinance** [comment]
Hi Real Shaman,

It would be greatly appreciated if you can let me know if it's OK to update
us on DeFiLlama that we're using Pyth.
Please let me know if there's any other things needed more.

Thanks,

2024년 1월 13일 (토) 오전 12:28, Shoe Bill ***@***.***>님이 작성:

**Comment by realdealshaman** [comment]
@ShoebillFinance sorry about the delay, I've updated to reflect the info as mentioned above, please let me know if anything changes and I'll be happy to help update it. Thanks for the PR

**Pull request merged**
