### PR TITLE
Update Mycelium information

### PR DESCRIPTION
**Pull request by rogue-hacker**
- Change Tracer DAO to Mycelium Perpetual Pools
- Change Mycelium.xyz to Mycelium Perpetual Swaps
- Add Mycelium Staking

Dependent on adapter update approval in https://github.com/DefiLlama/DefiLlama-Adapters/pull/4361

### CODE REVIEW

**Comment by Define101** [comment]
Regarding the first two, will get them done now
Point 3 only after the pr is merged and approved
Could we maintain Mycelium as the parentProtocol or should we change it?
image

**Comment by rogue-hacker** [comment]
Thank you @Define101.

Ideally we would like to maintain Mycelium as the parentProtocol to display the overall cumulative TVL of the three products we service. Would that be a problem?

**Comment by Define101** [comment]
No problem at all. 
Will let you know here once we have made the changes

**Comment by Define101** [comment]
Point 1 and 2 have been made
Changes should reflect on the website within 1 hour

**Comment by Define101** [comment]
Seems that everything is done
Can i close this PR?

**Comment by rogue-hacker** [comment]
Yes, everything looks good on the front-end. Thank you!

**Pull request closed without merging**
