### PR TITLE
update: ellipsis labs to phoenix

### PR DESCRIPTION
**Pull request by 0xkrane**
Updating naming for Ellipsis Labs to Phoenix. Ellipsis Labs is a company that contributes to Phoenix, which is the protocol whose data is being displayed on defillama (lmk if this is not the right place to push these changes and if i should start somewhere else)

The SVG was pulled from the Phoenix website (lmk if the sizing is ok; I've put it here as is but am happy to make changes if needed)

### CODE REVIEW

**Comment by eugene-chen** [comment]
thank you @0xkrane !

**Comment by Define101** [comment]
That logo will logo really bad, trust me.
May i suggest using the same as the twitter account?
image

**Comment by Define101** [comment]
I can make the changes, just need to know its ok

**Comment by 0xkrane** [comment]
let's use this:

Phoenix

**Comment by 0xkrane** [comment]
but yes works great otherwise (the image i added is just a higher quality version of the one you added)

**Pull request merged**
